// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvjcwpksbtgmtwjpfnda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2amN3cGtzYnRnbXR3anBmbmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjU3MDUsImV4cCI6MjA2NjY0MTcwNX0.dtl8fRB7DESQhRCpFlEtNL8wAIeLR_GLd_jLIxZsKls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);