// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thakqfwkkiuhxysgclxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYWtxZndra2l1aHh5c2djbHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTI0NzQsImV4cCI6MjA2NTUyODQ3NH0.fED18OOiHxuaBaErbxxdtvW5Ba9fmeZr9CiJbLhbH0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);